fn main() {
    return.is_failure //~ ERROR type annotations needed
}
